// <auto-generated />
using System;
using ConsultaCNPJ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultaCNPJ.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220923212938_DBinicial1")]
    partial class DBinicial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ConsultaCNPJ.Models.AtividadePrincipal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("RootID")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("RootID");

                    b.ToTable("AtividadePrincipal");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.AtividadesSecundaria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("RootID")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("RootID");

                    b.ToTable("AtividadesSecundaria");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Billing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("database")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("free")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Extra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Extra");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Qsa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("RootID")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("qual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("RootID");

                    b.ToTable("Qsa");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Root", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("abertura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("billingID")
                        .HasColumnType("int");

                    b.Property<string>("capital_social")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("data_situacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("data_situacao_especial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("efr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("extraID")
                        .HasColumnType("int");

                    b.Property<string>("fantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("motivo_situacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("municipio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("natureza_juridica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("porte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("situacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("situacao_especial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ultima_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("billingID");

                    b.HasIndex("extraID");

                    b.ToTable("roots");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.AtividadePrincipal", b =>
                {
                    b.HasOne("ConsultaCNPJ.Models.Root", null)
                        .WithMany("atividade_principal")
                        .HasForeignKey("RootID");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.AtividadesSecundaria", b =>
                {
                    b.HasOne("ConsultaCNPJ.Models.Root", null)
                        .WithMany("atividades_secundarias")
                        .HasForeignKey("RootID");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Qsa", b =>
                {
                    b.HasOne("ConsultaCNPJ.Models.Root", null)
                        .WithMany("qsa")
                        .HasForeignKey("RootID");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Root", b =>
                {
                    b.HasOne("ConsultaCNPJ.Models.Billing", "billing")
                        .WithMany()
                        .HasForeignKey("billingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultaCNPJ.Models.Extra", "extra")
                        .WithMany()
                        .HasForeignKey("extraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("billing");

                    b.Navigation("extra");
                });

            modelBuilder.Entity("ConsultaCNPJ.Models.Root", b =>
                {
                    b.Navigation("atividade_principal");

                    b.Navigation("atividades_secundarias");

                    b.Navigation("qsa");
                });
#pragma warning restore 612, 618
        }
    }
}
